services:
  pwn:
    build: .
    image: kind_author_pwn:latest 
    container_name: kind_author
    ports:
      - "13003:5000"
    privileged: true 
    environment:
      - JAIL_MEM=128M
      - JAIL_PID=20
      - JAIL_TIME=600
