services:
  pwn:
    build: .
    image: neural_net_pwn:latest 
    container_name: neural_net
    ports:
      - "13004:5000"
    privileged: true 
    environment:
      - JAIL_MEM=128M
      - JAIL_PID=20
      - JAIL_TIME=600
